export const images = {
    "1.jpg": "my birthday",
    "2.jpg":"take me to the moon",
    "3.jpg": "@Cville",
    "4.jpg":"6.1",
    "5.jpg": "first thing first",
    "6.jpg":"biubiubiu",
    "7.jpg": "rockaway",
    "8.jpg":"Cornell",
    "9.jpg": "Nigara",
    "10.jpg":"网友奔现",
    "11.jpg": "Houston",
    "12.jpg":"Happy Grads!",
    "13.jpg": "getaway前夜",
    "14.jpg":"一起租的第一辆车（车）",
    "15.jpg": "@catskill",
    "17.jpg": "跨年",
    "18.jpg":"修炼爱情",
    "19.jpg": "一起做蛋糕",
    "20.jpg":"早起爬山",
    "21.jpg": "@dc",
    "22.jpg":"@ivy creek",
    "23.jpg": "我怕怕quqqq",
    "24.jpg":"漂洋过海的礼物",
  };

 export const sizeLevel = ["xxs", "xs", "s", "m", "l","xl","xxl"]